# Generated by Django 2.0.6 on 2018-08-24 14:21

from django.db import migrations


def create_userplans(apps, schema_editor):
    from plans.models import CustomerPlan
    CustomerPlan.create_for_customers_without_plan()


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20200505_1819'),
    ]

    operations = [
        migrations.RunPython(create_userplans, reverse_code=migrations.RunPython.noop),
    ]
