# Generated by Django 2.2.11 on 2020-05-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_create_user_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerplan',
            options={'verbose_name': 'Customer plan', 'verbose_name_plural': 'Customers plans'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company', verbose_name='user'),
        ),
    ]
