# Generated by Django 5.2.6 on 2025-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_recurringuserplan_last_renewal_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='default',
            field=models.BooleanField(db_index=True, default=None, help_text='Both "Unknown" and "No" means that the plan is not default', null=True),
        ),
    ]
