# Generated by Django 6.0.3 on 2026-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0017_add_slug_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="userplan_active_before",
            field=models.BooleanField(
                blank=True,
                help_text="Snapshot of ``UserPlan.active`` taken before this order extended the user's plan. Doubles as the marker that a snapshot was taken: it's None for legacy orders completed before the snapshot fields existed and either True or False for new orders.",
                null=True,
                verbose_name="user plan active before",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="userplan_expire_before",
            field=models.DateField(
                blank=True,
                help_text="Snapshot of ``UserPlan.expire`` taken before this order extended the user's plan. Used to restore expire on refund.",
                null=True,
                verbose_name="user plan expire before",
            ),
        ),
    ]
