# Generated by Django 6.0.3 on 2026-06-02 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0018_order_userplan_snapshot_for_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="userplan_plan_before",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot of ``UserPlan.plan`` taken before this order extended the user's plan. Used to restore the plan on refund when the order is fully unwound: without it, refunding a first purchase (free -> paid) would leave the user on the paid plan with expire=None. None for legacy orders predating this field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.PLANS_PLAN_MODEL,
                verbose_name="user plan plan before",
            ),
        ),
    ]
