# Generated by Django 5.2.17 on 2026-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0020_normalize_non_default_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringuserplan",
            name="currency",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="currency"
            ),
        ),
    ]
