# Generated by Django 5.2.17 on 2026-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0021_alter_recurringuserplan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gross_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tax-inclusive total of the order, for orders priced tax-inclusive (e.g. a fixed amount charged by the payment provider). When set, it is the order total and the tax amount is the difference between it and the net amount; the net amount is then expected to be derived from it with net_from_gross(). Leave empty to compute the total from the net amount and the tax rate.",
                max_digits=7,
                null=True,
                verbose_name="gross amount",
            ),
        ),
    ]
