# Generated by Django 5.0.14 on 2025-06-07 16:36

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringuserplan",
            name="last_renewal_attempt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last renewal attempt"
            ),
        ),
    ]
