# Generated by Django 5.2.2 on 2025-06-19 12:00

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_plans", "0002_billinginfo_created_billinginfo_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Cancellation reason"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="credit_note_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_credit_notes",
                to="sample_plans.invoice",
                verbose_name="Credit note for",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Invoice"),
                    (2, "Invoice Duplicate"),
                    (3, "Order confirmation"),
                    (4, "Credit note"),
                ],
                db_index=True,
                default=1,
            ),
        ),
    ]
